name: greycell_app
description: GreyCells application.
version: 1.3.10+10

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  scoped_model: ^2.0.0
  connectivity: ^3.0.6
  shared_preferences: ^2.1.0
  font_awesome_flutter: ^10.4.0
  flutter_spinkit: ^5.1.0
  percent_indicator: ^4.2.3
  charts_flutter: ^0.12.0
  table_calendar: ^3.0.0
  package_info: ^2.0.2
  intl: ^0.17.0
  #  pdf: ^1.3.24

  flutter_launcher_icons: ^0.13.0
  cached_network_image: ^3.2.3

  flutter_svg: ^2.0.5

  flutter_html: ^3.0.0-alpha.6
  #  webview_flutter: ^0.3.22+1
  webview_flutter: ^4.1.0
  flutter_inappwebview: ^5.7.2+3

  pdf: ^3.10.1
  url_launcher: ^6.1.10
  open_file: ^3.2.1
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  printing: ^5.10.3

  flutter_share: ^2.0.0
#  image: ^2.1.12
  dio: ^5.1.1
  file_utils: ^1.0.1
  collection: ^1.17.0

  #for payment gateway
  razorpay_flutter: ^1.3.5


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/greycell_logo.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true
  assets:
    - assets/images/todole.png
    - assets/images/not_found.png
    - assets/images/help.png
    - assets/images/moon_error.png
    - assets/images/kspl.jpg
    - assets/images/greycell_logo.jpg
    - assets/images/done.png
    - assets/images/success.png
    - assets/images/failed.png
  #    - assets/src/index.html
  #    - assets/src/css/
  #    - assets/src/js/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
    